name: Backend build & tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install required workloads
        run: dotnet workload restore backend/NewsApp/NewsApp.sln

      - name: Build solution
        run: dotnet build backend/NewsApp/NewsApp.sln -c Release

      - name: Run tests
        run: dotnet test backend/NewsApp/NewsApp.sln -c Release --no-build --no-restore
